apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-backend-monitor
spec:
  selector:
    matchLabels:
      app: my-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s