apiVersion: apps/v1
kind : Deployment
metadata : 
  name: my-backend-apps
spec: 
  replicas:  {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: my-backend
  template : 
    metadata : 
      labels: 
        app: my-backend
    spec : 
      containers : 
      - name : app 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom : 
          - configMapRef : 
             name : my-backend-config
          - secretRef : 
             name : my-backend-secret
        ports: 
        - containerPort : 3000
        resources : 
          limits : 
            memory : "128Mi"
            cpu : "500m"
        livenessProbe : 
          httpGet:
            path : /
            port : 3000
          initialDelaySeconds : 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP