apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.6

        securityContext:
          allowPrivilegeEscalation: false

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage

        env:
        - name: POSTGRES_DB
          value: postgres

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-backend-secret
              key: DB_PASSWORD

        ports:
        - containerPort: 5432

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc