apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Jignesh4611/Terraform-AWS.git
    targetRevision: main
    path: my-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true